apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollouts-plugin-trafficrouter-contour
rules:
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - projectcontour.io
    resources:
      - httpproxies

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollouts-plugin-trafficrouter-contour
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollouts-plugin-trafficrouter-contour
